### ISSUE TITLE
Rewriting Docs

### ISSUE THREAD

**Issue by zamilskhan** [GluuFederation/docs-2.4.4-old#106]
Gluu Server Documentation
#1  Introduction

 1.1  Summary
 1.2  History
 1.3  Design Goals
 1.4  Architecture
#2  Installation Guide

 2.1  Preparing VM
 2.1.1  Azure Cloud
 2.1.2  Linode VM
 2.2  Single Setup
 2.2.1  Setup Script
 2.2.2  Ubuntu (maybe it is a good idea to put both ubuntu versions in the same page)
 2.2.3  CentOS
 2.2.4  RHEL
 2.2.5  Debian
 2.3  Cluster Setup
 2.3.1  Requirements
 2.3.2  Cluster Setup
#3  Administration Guide

 3.1  Login Page
 3.2  User Import
 3.2.1  Cache Refresh
 3.2.2  XLS File
 3.3  SAML
 3.3.1  Connecting SAML SP (Trust Relationship)
 3.3.2  Installing SAML SP (Ubuntu)
 3.3.3  Installing SAML SP (CentOS)
 3.3.4  Installing SAML SP (Windows/IIS7)
 3.3.5  Google
 3.3.6  Office 365
 3.3.7  Salesforce
 3.3.8  Dropbox
 3.3.9  Hobsons Education Solution
 3.4   ASIMBA
 3.5  OpenID
 3.5.1  Connecting OpenID Connect RP
 3.5.2  Installing OpenID Connect RP (Ubuntu)
 3.5.3  Installing OpenID Connect RP (CentOS)
 3.5.4  Liferay Plugin
 3.5.5  oxD Server (introduction and point to docs)
 3.6  Authentication 
 3.6.1  DUO
 3.6.2  U2F
 3.6.3  oxPush2
 3.6.4  SuperGluu
 3.6.5  Wikid
 3.6.6  Certificate 
 3.6.7  Google
#4  Reference Guide

 4.1  Customizing Login Page
 4.1.1  Restart Policy
 4.2   Custom Script / Interception Script

**Comment by zamilskhan** [comment]
@willow9886

**Comment by nynymike** [comment]
Just a few notes:

1. I don't like the term "user" ... it makes me think of an opium junkie... I prefer "Person" or "People" 
2. We can drop Liferay plugin... that's hasn't been tested in some time
3. User Guide and Admin Guide are sort of the same... because the Admin is the user...
4. I wonder if we should have a section about Customizing the Gluu Server, including writing interception scripts (we have many...), how to make custom schema, how to customize the UI. 
5. I wonder if we should have a section about authentication. We have many types of authentication, and people have tons fo questions about this. Also we have native support for FIDO U2F and UAF endpoints.
6. We need links to OpenID Connect Native Java Libraries that we support
7. Why is there no section about Access Management with sub-sections about UMA and OAuth2 (GAT token)

**Comment by yurem** [comment]
We need to add information about customization. I still see many questions about how to to restore login page customizations...
```
CE 2.4.3 during install creates next folders:
1)      /var/gluu/webapps/oxauth/{libs, pages, resources}
2)      /var/gluu/webapps/oxtrust/{libs, pages, resources}
 
The solution is almost similar for oxAuth and oxTrust. I will explain only one for oxAuth.

/var/gluu/webapps/oxauth/libs we can use it to add custom 3-rd party libs which custom scripts uses in oxAuth.
/var/gluu/webapps/oxauth/pages we uses it to override/add new pages to oxAuth. Example: login.xhtml /var/gluu/webapps/oxauth/resources we can use to add images, styles, other resources. oxAuth maps them to /oxauth/ext/resources . Example: http://ce-dev.gluu.org/oxauth/ext/resources

Tomcat restart policy:
1.	On “libs” update we always need to restart tomcat. It’s not problem because we adds custom libs very rarely on integration phase.
2.	On “resources” update we don’t need to restart tomcat.
3.	On “pages” update we should restart tomcat only in few cases:
 - 	When we override default page. We need to that only on custom page creation first time because JSF may cache path to original version
 -	When we remove page. We need to restart tomcat on replace context with empty page to invalidate it.
New environment variable:
In these 3 solutions I used environment variable to avoid hard coding or changing applications configurations. Here is new tomcat wrapper variable:
wrapper.java.additional.20=-Dgluu.external.resource.base=/var/gluu/webapps
```

**Comment by zamilskhan** [comment]
@nynymike Sensei, then we can have the Admin guide where the tutorials will be put and as Will suggested, a Reference Guide where we can put in the customization, schema and other related material can go.

**Comment by zamilskhan** [comment]
Keeping track of content for the new Administration Guide for collaboration. Please feel free to edit

https://docs.google.com/document/d/146tpPhGoUycFBCuG4tAtX46JpXsC4fVLEQVENN21KTk/edit?usp=sharing

**Comment by jschristie** [comment]
@zamilskhan,

for which version of the product is this? is it for 2.4.4 or 3.0?
