### ISSUE TITLE
oxTrust / oxAuth Configuration documentation

### ISSUE THREAD

**Issue by mzico** [GluuFederation/docs-2.4.4-old#81]
Let's make sure these fields are documented with proper screenshot. 
Configuration --> JSON Configuration --> 
![json_configuration](https://cloud.githubusercontent.com/assets/7156097/14147413/0465d39c-f661-11e5-8f47-c03b89940ec9.png)

**Comment by aveekbu** [comment]
I'll check with @zamilskhan and make it done! 

Thanks!

**Comment by mzico** [comment]
@aveekbu : What's the status of this doc? We need it now....

**Comment by mzico** [comment]
reassigning to @zamilskhan . We need this doc to be published.

**Comment by zamilskhan** [comment]
@mzico check. pushed updates now

**Comment by mzico** [comment]
@zamilskhan : thanks for the skeleton!! I'll add explanations there

**Comment by zamilskhan** [comment]
np :) I'll take a look again tomorrow and add whatever I can

**Comment by zamilskhan** [comment]
close issue?

**Comment by mzico** [comment]
No.. can you please add a ticket for me in Trello on this?
